### ISSUE TITLE
A few bugs & space to improve

### ISSUE THREAD

**Issue by Xflick** [DamnTricker996/21-digree#3]
Things to be fixed:
1. When I input "Y" or "N", the program shows that the input is invalid.
2. When I input "fsdfsd" or something like this, the "try again" message will be shown many times. Maybe you define input as a char, and it will cause this bug.
3. When I input "n" with only two cards in my hand, the program will show the result directly instead of showing what card computer gets.
4. When I want to play again, the program will show "Dude" first.
5. The program is difficult to understand because of the variable name.
6. I don't know some English words in your code, such as "plum", "pades", "refold" or something else.

**Comment by DamnTricker996** [comment]
1. Thanks, but I don't want it to process when Y or N is input.
2. Very observant, thanks.
3. Like the last one.
4. Not true.
5. ....
6. ....

Thank you!
